import math

def _sigmoid(x, center, steepness):
    """Maps a value to 0-1 using a sigmoid curve centered at 'center'."""
    return 1.0 / (1.0 + math.exp(-steepness * (x - center)))


def generate_reasoning(c2pa_result, sightengine_result, spectral_result, physics_result=None, hue_result=None):
    """
    Aggregates results from 5 distinct forensic layers and generates a
    human-readable explanation with research-calibrated confidence scoring.
    
    Layers:
        1. C2PA Cryptographic Provenance        (weight: 1.0 — definitive when present)
        2. Sightengine Neural Detection (API)    (weight: 0.8 — commercial ML model)
        3. Spectral FFT Azimuthal PSD            (weight: 0.5 — frequency domain physics)
        4. Physics / ELA + Sensor Noise          (weight: 0.6 — compression + noise forensics)
        5. YCbCr + CFA Demosaicing Trace         (weight: 0.7 — camera physics fingerprint)
    """
    weights = {"c2pa": 1.0, "sightengine": 0.8, "spectral": 0.5, "physics": 0.6, "hue": 0.7}
    
    total_weight = 0
    accumulated_score = 0
    
    reasons = []
    ai_attribution = "Unknown"
    
    # Initialize all confidences to 0.0 to prevent UnboundLocalError if a layer fails
    sight_conf = 0.0
    fft_ai_conf = 0.0
    physics_ai_conf = 0.0
    hue_ai_conf = 0.0
    
    # ============================================================
    # Layer 1: C2PA Cryptographic Provenance
    # ============================================================
    c2pa_detected = c2pa_result.get("detected", False)
    c2pa_category = "Unknown"
    
    if c2pa_detected:
        generator = c2pa_result.get("generator", "an AI tool").lower()
        ai_attribution = c2pa_result.get("generator", "an AI tool")
        software_agent = c2pa_result.get("software_agent", "")
        action_type = c2pa_result.get("action_type", "")
        has_ingredients = c2pa_result.get("has_ingredients", False)
        
        # Use software_agent if available (more specific than generator)
        display_name = software_agent if software_agent else ai_attribution
        
        if any(cam in generator for cam in ['nikon', 'leica', 'sony', 'canon', 'truepic', 'samsung', 'apple', 'google pixel']):
            c2pa_category = "Camera"
            reasons.append(f"Image contains a hardware-level C2PA signature from **{display_name}**, proving it is a genuine photograph.")
            accumulated_score += 0.0 * weights['c2pa']
        elif any(ai in generator for ai in ['midjourney', 'dall-e', 'firefly', 'bing', 'stable diffusion', 'microsoft', 'openai', 'stability']):
            c2pa_category = "AI"
            reasons.append(f"Image contains a C2PA signature confirming it was generated by **{display_name}**.")
            accumulated_score += 1.0 * weights['c2pa']
        else:
            c2pa_category = "Editor"
            detail = f"Image has a C2PA signature from **{display_name}**."
            if action_type:
                detail += f" Action: `{action_type}`."
            if has_ingredients:
                detail += " Image was derived from another source."
            reasons.append(detail)
            accumulated_score += 0.3 * weights['c2pa']
            
        total_weight += weights['c2pa']

    # ============================================================
    # Layer 2: Sightengine API
    # ============================================================
    sightengine_score = sightengine_result.get("score", 0.0)
    if not sightengine_result.get("error"):
        accumulated_score += sightengine_score * weights['sightengine']
        total_weight += weights['sightengine']
        
        if sightengine_score > 0.8:
            reasons.append(f"Sightengine commercial detection spotted strong synthetic artifacts ({(sightengine_score*100):.1f}% confidence).")
        elif sightengine_score > 0.5:
            reasons.append(f"Sightengine noticed patterns consistent with AI generation ({(sightengine_score*100):.1f}% confidence).")
        else:
            reasons.append(f"Sightengine found the image looks highly authentic ({(sightengine_score*100):.1f}% AI score).")
            
        engines = sightengine_result.get("engines", [])
        if engines and ai_attribution == "Unknown" and sightengine_score > 0.5:
            ai_attribution = engines[0]['engine']

    # ============================================================
    # Layer 3: Spectral FFT Analysis (Azimuthal PSD)
    # ============================================================
    if spectral_result.get('status') == 'success':
        beta = spectral_result.get('fft_beta', 2.0)
        num_peaks = spectral_result.get('fft_peaks', 0)
        r_squared = spectral_result.get('fft_r_squared', 0.9)
        details = spectral_result.get('details', '')
        
        # Spectral decay scoring using sigmoid
        # beta < 1.0 → AI (GAN), beta 0.9-2.5 → real, beta > 2.8 → AI (diffusion)
        fft_ai_conf = 0.0
        
        if beta < 0.8:
            fft_ai_conf = 0.90   # Strong GAN signature
        elif beta < 1.0:
            fft_ai_conf = 0.65   # Weak GAN signature
        elif beta > 3.0:
            fft_ai_conf = 0.80   # Diffusion over-smoothness
        elif beta > 2.6:
            fft_ai_conf = 0.55   # Slight diffusion
        else:
            fft_ai_conf = 0.15   # Natural range
        
        # Boost if periodic peaks found (GAN checkerboard)
        if num_peaks >= 5:
            fft_ai_conf = min(1.0, fft_ai_conf + 0.20)
        elif num_peaks >= 3:
            fft_ai_conf = min(1.0, fft_ai_conf + 0.10)
        
        # Penalize poor fit quality
        if r_squared < 0.7:
            fft_ai_conf = min(1.0, fft_ai_conf + 0.10)
        
        accumulated_score += fft_ai_conf * weights['spectral']
        total_weight += weights['spectral']
        
        if fft_ai_conf > 0.4:
            reasons.append(f"**Spectral FFT:** {details}")

    # ============================================================
    # Layer 4: Physics / ELA + Sensor Noise
    # ============================================================
    if physics_result and physics_result.get('status') == 'success':
        noise_var = physics_result.get('noise_variance', 100.0)
        noise_kurt = physics_result.get('noise_kurtosis', 3.0)
        spatial_unif = physics_result.get('noise_spatial_uniformity', 0.5)
        ela_multi_std = physics_result.get('ela_multi_std', 2.0)
        physics_details = physics_result.get('details', '')
        
        physics_ai_conf = 0.0
        
        # Signal 1: Noise variance (strongest physics signal)
        if noise_var < 1.0:
            physics_ai_conf = 0.95   # Essentially zero noise → definitive AI
        elif noise_var < 5.0:
            physics_ai_conf = 0.70
        else:
            physics_ai_conf = 0.10
        
        # Signal 2: Noise kurtosis (only trust if it's extremely low which means flat noise)
        if noise_kurt == 0.0:
            physics_ai_conf = max(physics_ai_conf, 0.85)  # No measurable noise
        
        # Signal 3: Spatial uniformity
        if spatial_unif > 0.80:
            physics_ai_conf = max(physics_ai_conf, 0.60)
        
        # Signal 4: Multi-quality ELA uniformity
        if ela_multi_std < 0.5:
            physics_ai_conf = max(physics_ai_conf, 0.55)
        
        accumulated_score += physics_ai_conf * weights['physics']
        total_weight += weights['physics']
        
        if physics_ai_conf > 0.4:
            reasons.append(f"**Physics/ELA:** {physics_details}")

    # ============================================================
    # Layer 5: YCbCr + CFA Demosaicing Trace
    # ============================================================
    if hue_result and hue_result.get('status') == 'success':
        # The hue layer now provides its own combined confidence
        hue_confidence = hue_result.get('hue_confidence', 0.0)
        cfa_trace = hue_result.get('cfa_trace_strength', 0.0)
        disconnect_score = hue_result.get('edge_density_score', 0.0)
        hue_details = hue_result.get('details', '')
        
        # Use the pre-computed combined confidence directly
        hue_ai_conf = hue_confidence
        
        accumulated_score += hue_ai_conf * weights['hue']
        total_weight += weights['hue']
        
        if hue_ai_conf > 0.35:
            reasons.append(f"**CFA/Chrominance:** {hue_details}")
        elif cfa_trace > 0.10:
            reasons.append(f"**CFA/Chrominance:** Bayer camera pattern detected (trace: {cfa_trace:.3f}) — consistent with real camera.")

    # ============================================================
    # Calculate final blended confidence
    # ============================================================
    # Base baseline confidence
    if total_weight > 0:
        base_confidence = accumulated_score / total_weight
    else:
        base_confidence = 0.0

    # Max-evidence aggregation: forensic signals shouldn't average out. 
    # If one strong layer detects an anomaly, it shouldn't be canceled by a neutral layer.
    layer_confidences = [
        sight_conf, 
        fft_ai_conf, 
        physics_ai_conf, 
        hue_ai_conf
    ]
    max_conf = max(layer_confidences)
    
    if max_conf > 0.85:
        # Heavily weight the strongest signal
        final_confidence = (base_confidence * 0.2) + (max_conf * 0.8)
    elif max_conf > 0.65:
        # Moderately boost
        final_confidence = (base_confidence * 0.5) + (max_conf * 0.5)
    else:
        final_confidence = base_confidence

    final_confidence = max(0.0, min(1.0, final_confidence))

    # ============================================================
    # Formulate Verdict
    # ============================================================
    if final_confidence > 0.65:
        verdict = "AI-Generated"
        summary = "Based on aggregate 5-layer analysis, this image is classified as AI-generated."
    elif final_confidence > 0.35:
        verdict = "Suspicious / Edited Photo"
        summary = "The results are mixed. The image may have been digitally altered or heavily edited."
    else:
        verdict = "Real Camera"
        summary = "This image appears to be a genuine photograph based on the forensic analysis."

    # C2PA definitive overrides
    if c2pa_category == "Camera":
        final_confidence = 0.0
        verdict = "Real Camera"
        summary = f"Definitively Real. A cryptographic hardware signature from {ai_attribution} proves this image was captured by a camera."
    elif c2pa_category == "AI":
        final_confidence = 1.0
        verdict = "AI-Generated"
        summary = f"Definitively AI-generated. A cryptographic C2PA signature from {ai_attribution} proves this."

    return {
        "verdict": verdict,
        "confidence": round(final_confidence, 3),
        "generator": ai_attribution,
        "summary": summary,
        "detailed_reasons": reasons
    }
