def generate_reasoning(c2pa_result, sightengine_result, spectral_result, physics_result=None, hue_result=None):
    """
    Aggregates results from 5 distinct forensic layers and generates a
    human-readable explanation with weighted confidence scoring.
    
    Layers:
        1. C2PA Cryptographic Provenance
        2. Sightengine Neural Artifact Detection (API)
        3. Spectral FFT Analysis (GAN vs Diffusion)
        4. Physics / ELA + Sensor Noise
        5. YCbCr Chrominance Disconnect (Hue)
    """
    weights = {"c2pa": 1.0, "sightengine": 0.8, "spectral": 0.4, "physics": 0.6, "hue": 0.5}
    
    total_weight = 0
    accumulated_score = 0
    
    reasons = []
    ai_attribution = "Unknown"
    
    # ============================================================
    # Layer 1: C2PA Cryptographic Provenance
    # ============================================================
    c2pa_detected = c2pa_result.get("detected", False)
    c2pa_category = "Unknown"
    
    if c2pa_detected:
        generator = c2pa_result.get("generator", "an AI tool").lower()
        ai_attribution = c2pa_result.get("generator", "an AI tool")
        
        if any(cam in generator for cam in ['nikon', 'leica', 'sony', 'canon', 'truepic']):
            c2pa_category = "Camera"
            reasons.append(f"Image contains a hardware-level C2PA signature from **{ai_attribution}**, proving it is a genuine photograph.")
            accumulated_score += 0.0 * weights['c2pa']
        elif any(ai in generator for ai in ['midjourney', 'dall-e', 'firefly', 'bing', 'stable diffusion', 'microsoft', 'openai']):
            c2pa_category = "AI"
            reasons.append(f"Image contains a C2PA signature confirming it was generated by **{ai_attribution}**.")
            accumulated_score += 1.0 * weights['c2pa']
        else:
            c2pa_category = "Editor"
            reasons.append(f"Image has a C2PA signature from **{ai_attribution}**. This tracks provenance but doesn't strictly mean it was AI generated.")
            accumulated_score += 0.2 * weights['c2pa']
            
        total_weight += weights['c2pa']

    # ============================================================
    # Layer 2: Sightengine API (Commercial Deep Learning model)
    # ============================================================
    sightengine_score = sightengine_result.get("score", 0.0)
    if not sightengine_result.get("error"):
        accumulated_score += sightengine_score * weights['sightengine']
        total_weight += weights['sightengine']
        
        if sightengine_score > 0.8:
            reasons.append(f"Sightengine commercial detection spotted strong synthetic artifacts ({(sightengine_score*100):.1f}% confidence).")
        elif sightengine_score > 0.5:
            reasons.append(f"Sightengine commercial detection noticed some unusual patterns consistent with AI generation ({(sightengine_score*100):.1f}% confidence).")
        else:
            reasons.append(f"Sightengine algorithms found the image looks highly authentic, lacking typical AI artifacts.")
            
        engines = sightengine_result.get("engines", [])
        if engines and ai_attribution == "Unknown" and sightengine_score > 0.5:
            ai_attribution = engines[0]['engine']

    # ============================================================
    # Layer 3: Spectral FFT Analysis (GAN vs Diffusion)
    # ============================================================
    if spectral_result.get('status') == 'success':
        fft_score = spectral_result.get('fft_score', 0.0)
        generator_type = spectral_result.get('generator_type', 'Unknown')
        details = spectral_result.get('details', '')
        
        # The FFT layer contributes a confidence value
        fft_ai_conf = 0.0
        if fft_score > 0.150:
            fft_ai_conf = 0.8  # GAN spikes
            reasons.append(f"**Spectral FFT:** {details}")
        elif fft_score < 0.095:
            fft_ai_conf = 0.7  # Diffusion smoothness
            reasons.append(f"**Spectral FFT:** {details}")
        else:
            fft_ai_conf = 0.2  # Normal
        
        accumulated_score += fft_ai_conf * weights['spectral']
        total_weight += weights['spectral']

    # ============================================================
    # Layer 4: Physics / ELA + Sensor Noise
    # ============================================================
    if physics_result and physics_result.get('status') == 'success':
        ela_var = physics_result.get('ela_variance', 0.0)
        noise_var = physics_result.get('noise_variance', 100.0)
        physics_details = physics_result.get('details', '')
        
        physics_ai_conf = 0.0
        if noise_var < 5.0:
            physics_ai_conf = 0.95  # Zero sensor noise = definitive AI
            reasons.append(f"**Physics/ELA:** Zero camera sensor noise detected (Noise: {noise_var:.2f}). This is physically impossible for a real camera.")
        elif ela_var > 1.25 and noise_var < 80.0:
            physics_ai_conf = 0.75
            reasons.append(f"**Physics/ELA:** Inconsistent compression mapping detected (ELA: {ela_var:.2f}).")
        else:
            physics_ai_conf = 0.15
            
        accumulated_score += physics_ai_conf * weights['physics']
        total_weight += weights['physics']

    # ============================================================
    # Layer 5: YCbCr Chrominance Disconnect (Hue)
    # ============================================================
    if hue_result and hue_result.get('status') == 'success':
        disconnect_score = hue_result.get('edge_density_score', 0.0)
        hue_details = hue_result.get('details', '')
        
        hue_ai_conf = 0.0
        if disconnect_score > 0.35:
            hue_ai_conf = 0.80
            reasons.append(f"**Chrominance Analysis:** {hue_details}")
        else:
            hue_ai_conf = 0.15
            
        accumulated_score += hue_ai_conf * weights['hue']
        total_weight += weights['hue']

    # ============================================================
    # Calculate final blended confidence (0 to 1)
    # ============================================================
    if total_weight > 0:
        final_confidence = accumulated_score / total_weight
    else:
        final_confidence = 0.0
    
    # Clamp
    final_confidence = max(0.0, min(1.0, final_confidence))

    # ============================================================
    # Formulate Verdict
    # ============================================================
    if final_confidence > 0.65:
        verdict = "AI-Generated"
        summary = "Based on aggregate 5-layer analysis, this image is classified as AI-generated."
    elif final_confidence > 0.35:
        verdict = "Suspicious / Edited Photo"
        summary = "The results are mixed. The image may have been digitally altered or heavily edited."
    else:
        verdict = "Real Camera"
        summary = "This image appears to be a genuine photograph based on the metadata and pixel forensics."

    # C2PA overrides: Hardware camera = Real, AI signature = Fake
    if c2pa_category == "Camera":
        final_confidence = 0.0
        verdict = "Real Camera"
        summary = f"Definitively Real. A cryptographic hardware signature from {ai_attribution} proves this image was captured by a camera and has not been altered."
    elif c2pa_category == "AI":
        final_confidence = 1.0
        verdict = "AI-Generated"
        summary = f"This image is definitively AI-generated. A cryptographic signature proves it."

    return {
        "verdict": verdict,
        "confidence": final_confidence,
        "generator": ai_attribution,
        "summary": summary,
        "detailed_reasons": reasons
    }
