def generate_reasoning(c2pa_result, sightengine_result, spectral_result):
    """
    Aggregates results from 3 distinct layers and generates a human-readable explanation.
    """
    score = 0
    weights = {"c2pa": 1.0, "sightengine": 0.8, "spectral": 0.4}  # Trust weights
    
    total_weight = 0
    accumulated_score = 0
    
    reasons = []
    ai_attribution = "Unknown"
    
    # Layer 1: C2PA Metadata
    c2pa_detected = c2pa_result.get("detected", False)
    c2pa_category = "Unknown"
    
    if c2pa_detected:
        generator = c2pa_result.get("generator", "an AI tool").lower()
        ai_attribution = c2pa_result.get("generator", "an AI tool")
        
        # Categorize the C2PA signature
        if any(cam in generator for cam in ['nikon', 'leica', 'sony', 'canon', 'truepic']):
            c2pa_category = "Camera"
            reasons.append(f"Image contains a hardware-level C2PA signature from **{ai_attribution}**, proving it is a genuine photograph.")
            accumulated_score += 0.0 * weights['c2pa'] # 0% AI
        elif any(ai in generator for ai in ['midjourney', 'dall-e', 'firefly', 'bing', 'stable diffusion', 'microsoft', 'openai']):
            c2pa_category = "AI"
            reasons.append(f"Image contains a C2PA signature confirming it was generated by **{ai_attribution}**.")
            accumulated_score += 1.0 * weights['c2pa'] # 100% AI
        else:
            c2pa_category = "Editor"
            # It's an editor or a test script (like Photoshop, Lightroom, make_test_images)
            reasons.append(f"Image has a C2PA signature from **{ai_attribution}**. This tracks provenance but doesn't strictly mean it was AI generated.")
            # Don't heavily skew the AI score if it's just Photoshop; let Sightengine and Spectral decide.
            accumulated_score += 0.2 * weights['c2pa'] 
            
        total_weight += weights['c2pa']
    else:
        # Absence of C2PA doesn't mean it's real, it just means no cert.
        pass

    # Layer 2: Sightengine API (Commercial Deep Learning model)
    sightengine_score = sightengine_result.get("score", 0.0)
    if not sightengine_result.get("error"):
        accumulated_score += sightengine_score * weights['sightengine']
        total_weight += weights['sightengine']
        
        if sightengine_score > 0.8:
            reasons.append(f"Sightengine commercial detection spotted strong synthetic artifacts ({(sightengine_score*100):.1f}% confidence).")
        elif sightengine_score > 0.5:
            reasons.append(f"Sightengine commercial detection noticed some unusual patterns consistent with AI generation ({(sightengine_score*100):.1f}% confidence).")
        else:
            reasons.append(f"Sightengine algorithms found the image looks highly authentic, lacking typical AI artifacts.")
            
        engines = sightengine_result.get("engines", [])
        if engines and ai_attribution == "Unknown" and sightengine_score > 0.5:
            ai_attribution = engines[0]['engine'] # e.g. 'Sightengine GenAI Model'

    # Layer 3: Spectral FFT Analysis (GAN vs Diffusion)
    if spectral_result.get('status') == 'success':
        fft_score = spectral_result.get('fft_score', 0.0)
        generator_type = spectral_result.get('generator_type', 'Unknown')
        details = spectral_result.get('details', '')
        
        if sightengine_score > 0.5 or c2pa_category == "AI":
            reasons.append(f"**Spectral FFT Analysis:** {details} Suggests genesis via {generator_type}.")
        else:
            pass

    # Calculate final blended confidence (0 to 1)
    if total_weight > 0:
        final_confidence = accumulated_score / total_weight
    else:
        final_confidence = 0.0 # Error state
        
    # Formulate final verdict text based on the final blended confidence
    if final_confidence > 0.65:
        verdict = "AI-Generated"
        summary = "Based on aggregate analysis, this image is classified as AI-generated."
    elif final_confidence > 0.35:
        verdict = "Suspicious"
        summary = "The results are mixed. The image may have been digitally altered or heavily edited."
    else:
        verdict = "Real Camera"
        summary = "This image appears to be a genuine photograph based on the metadata and pixel forensics."

    # If it's a guaranteed hardware camera signature, override everything to Real!
    if c2pa_category == "Camera":
        final_confidence = 0.01  # Need a tiny bit of float to avoid zero logic division elsewhere
        verdict = "Real Camera"
        summary = f"Definitively Real. A cryptographic hardware signature from {ai_attribution} proves this image was captured by a camera and has not been altered."
    # If it's a guaranteed AI signature, override to Fake!
    elif c2pa_category == "AI":
        final_confidence = 1.0
        verdict = "AI-Generated"
        summary = f"This image is definitively AI-generated. A cryptographic signature proves it."

    return {
        "verdict": verdict,
        "confidence": final_confidence,
        "generator": ai_attribution,
        "summary": summary,
        "detailed_reasons": reasons
    }
